import { MetadataSourceAuthorship } from './metadata-source-authorship';

export enum MetadataSource {
  Manual = 'Curated',
  Import = 'Imported from a third-party database',
  AI = 'Generated by artificial intelligence',
}

export class Metadata {
  source: MetadataSource;
  authorship: MetadataSourceAuthorship;
  updatedAt?: Date;

  constructor(properties: {
    source: MetadataSource;
    authorship: MetadataSourceAuthorship;
    updatedAt?: Date;
  }) {
    Object.assign(this, properties);
    this.updatedAt = this.updatedAt ?? new Date();
  }
}
